# Generated by Django 4.2.6 on 2023-10-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_pdf_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='pdf',
        ),
    ]
